# Install the apt prerequisites
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hugo

# Build the website
script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: gh-pages
