dist: bionic
before_install:
  sudo apt-get install hugo
script:
  - hugo
before_deploy:   
  - cp data/README.md docs/README.md
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: yochannah/intermine.github.io
  target_branch: master
  on:
    branch: travis-deploy-tests
